# Generated by Django 5.0.9 on 2026-08-31 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_alter_organizationmember_options_and_more"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmember",
            options={},
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="project",
            name="key",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="project",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="organizations.organization",
            ),
        ),
    ]
